package report

var severityOverrides = map[string]Severity{
	"PII_LEAKAGE_EMAIL":                       SeverityLow,
	"RETRY_AFTER_HEADER_MISSING":              SeverityInfo,
	"X_RATELIMIT_HEADERS_MISSING":             SeverityLow,
	"SESSION_MANAGEMENT_MANUAL_REVIEW_NEEDED": SeverityInfo,
	"IDOR_POSSIBLE":                           SeverityMedium,
	"IDOR_RESOURCE_GUESSING":                  SeverityLow,
	"IDOR_PASSIVE_INDICATOR":                  SeverityInfo,
	"METHOD_OVERRIDE_PASSIVE_INDICATOR":       SeverityInfo,
	"PARAMETER_POLLUTION_PASSIVE_INDICATOR":   SeverityInfo,
	"SSRF_PASSIVE_INDICATOR":                  SeverityInfo,
	"SSRF_INTERNAL_TARGET_IN_INPUT":           SeverityLow,
	"SSRF_UNSAFE_SCHEME_IN_INPUT":             SeverityMedium,
	"SSRF_CLOUD_METADATA_ACCESS_DETECTED":     SeverityHigh,
	"JSON_UNEXPECTED_FIELD_PASSIVE_INDICATOR": SeverityInfo,
	"SQL_INJECTION_PASSIVE_INDICATOR":         SeverityInfo,
	"REFLECTED_XSS_PASSIVE_INDICATOR":         SeverityInfo,
	"DOM_XSS_POSSIBLE":                        SeverityMedium,
	"DOM_XSS_RISKY_SOURCE_SINK":               SeverityLow,
	"DOM_XSS_ACTIVE_PROBABLE":                 SeverityMedium,
	"DOM_XSS_ACTIVE_SIGNAL":                   SeverityLow,
	"AUTH_CONTEXT_DIFFERENCE":                 SeverityLow,
	"RATE_LIMIT_NOT_ENFORCED_ACTIVE":          SeverityMedium,
	"CHAIN_XSS_TO_SESSION_RISK":               SeverityHigh,
	"CHAIN_TOKEN_TO_IDOR_RISK":                SeverityHigh,
	"INFORMATION_LEAKAGE_X_POWERED_BY":        SeverityInfo,
	"INFORMATION_LEAKAGE_SERVER_HEADER":       SeverityInfo,
	"INFORMATION_LEAKAGE_FRAMEWORK_SIGNATURE": SeverityLow,
	"SERVER_HEADER_EXPOSED":                   SeverityInfo,
	"X_POWERED_BY_EXPOSED":                    SeverityInfo,
	"CONSOLE_LOG_EXPOSED":                     SeverityInfo,
	"IFRAME_SANDBOX_MISSING":                  SeverityLow,
	"SENSITIVE_API_KEY_FOUND":                 SeverityMedium,
	"INFORMATION_LEAKAGE_STACK_TRACE":         SeverityMedium,
	"METHOD_OVERRIDE_ALLOWED":                 SeverityLow,
	"AUTH_SURFACE_PROFILE":                    SeverityInfo,
	"CACHE_PUBLIC_WITH_SET_COOKIE":            SeverityMedium,
	"CACHE_VARY_KEY_WEAK":                     SeverityLow,
	"REQUEST_SMUGGLING_PASSIVE_INDICATOR":     SeverityInfo,
	"CSP_POLICY_WEAK":                         SeverityMedium,
	"API_CONTRACT_DRIFT_PASSIVE":              SeverityInfo,
	"CORS_WILDCARD_WITH_CREDENTIALS":          SeverityHigh,
	"CORS_NULL_ORIGIN_ALLOWED":                SeverityMedium,
	"CORS_MULTI_ORIGIN_REFLECTION":            SeverityHigh,
	"HOST_HEADER_INJECTION_POSSIBLE":          SeverityHigh,
	"CACHE_POISONING_ACTIVE_SIGNAL":           SeverityHigh,
	"CSRF_TOKEN_REPLAY_POSSIBLE":              SeverityLow,
	"JWT_ALG_NONE_ACCEPTED":                   SeverityHigh,
	"FILE_UPLOAD_BYPASS_POSSIBLE":             SeverityMedium,
	"FILE_UPLOAD_EXECUTION_POSSIBLE":          SeverityHigh,
	"GRAPHQL_AUTH_BOUNDARY_WEAK":              SeverityMedium,
	"OPEN_REDIRECT_SCRIPT_SCHEME":             SeverityHigh,
	"ASI_EXTERNAL_ASSET_DISCOVERED":           SeverityInfo,
	"ASI_SUBDOMAIN_DISCOVERED":                SeverityInfo,
	"ASI_EXPOSED_ENDPOINT":                    SeverityLow,
	"ASI_EXPOSED_ENDPOINT_REFERENCE":          SeverityLow,
	"ASI_SHADOW_API_CANDIDATE":                SeverityLow,
	"ASI_PUBLIC_BUCKET_REFERENCE":             SeverityInfo,
	"ASI_API_DOCS_REFERENCE":                  SeverityLow,
	"ASI_WEBSOCKET_ENDPOINT_REFERENCE":        SeverityInfo,
	"ASI_DEV_ARTIFACT_REFERENCE":              SeverityInfo,
	"ASI_SHADOW_API_VERIFIED":                 SeverityMedium,
	"ASI_SHADOW_API_RESTRICTED":               SeverityInfo,
	"ASI_EXPOSED_ENDPOINT_VERIFIED":           SeverityMedium,
	"ASI_API_DOCS_EXPOSED":                    SeverityMedium,
	"ASI_PUBLIC_BUCKET_ACCESSIBLE":            SeverityMedium,
	"ASI_PUBLIC_BUCKET_RESTRICTED":            SeverityInfo,
}

func ApplySeverityOverride(f Finding) Finding {
	if sev, ok := severityOverrides[f.ID]; ok {
		f.Severity = sev
	}
	return f
}
